Global:
  outdir: /cluster/work/bewi/members/dondia/projects/long_reads_tree/LongSom_out
  data: /cluster/work/bewi/members/dondia/projects/long_reads_tree/data/SComatic_input
  scomatic: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/SComatic/scripts
  annovar: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/annovar
  genome: /cluster/work/bewi/members/dondia/projects/ovarian_cancer/reference/hg38.fa
  ids:
    B486: ""
    B497: ""
    B500: ""

PoN:
  celltypes:
    Normal: ""
  ids:
    B486_Norm: ""
    B500_Norm: ""
  min_ac_cells: 1
  min_ac_reads: 1
  min_cells: 1
  min_cell_types: 1

CellTypeReannotation:
  cancer_ctype: HGSOC
  min_variants: 2
  celltypes:
    HGSOC: ""
    Non-HGSOC: ""

SNVCalling:
  cancer_ctype: Cancer
  celltypes:
    Cancer: ""
    NonCancer: ""
  min_ac_reads: 5
  clust_dist: 10000

scDNA:
  Calling:
    Tumor_clone: 'Clone_Tum'
    NonTumor_clone: 'Clone_NonTum'
    BaseCellCounter:
      min_mapping_quality: 60
      min_dp: 5
      min_cc: 5  
    BaseCellCalling:
      min_ac_reads: 5
  Validation:
    BaseCellCounter:
      min_mapping_quality: 50
      min_dp: 1
      min_cc: 1
    BaseCellCalling:
      min_ac_cells: 1
      min_ac_reads: 1
      min_cells: 1
      min_cell_types: 1

SComatic:
  chrM_contaminant: 'True'
  BaseCellCounter:
    min_mapping_quality: 60
    chromosomes: all  

  BaseCellCalling:
    Min_cell_types: 2
    RNA_editing: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/SComatic/RNAediting/AllEditingSites.hg38.txt
    min_distance: 5
    PoN_SR: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/SComatic/PoNs/PoN.scRNAseq.hg38.NochrM.tsv
    gnomAD_db: /cluster/work/bewi/members/dondia/projects/long_reads_tree/ref/gnomAD
    max_gnomAD_VAF: 0.01
    deltaVAF: 0.25
    deltaCCF: 0.4

  HCCV:
    deltaVAF: 0.25
    deltaCCF: 0.4

  SingleCellGenotype:
    alt_flag: All
    pvalue: 0.01

BnpC:
  mcmc_steps: 2000
  outdir: test
  missdata: ''
  cup: 0
  eup: 1e-9
  FP: -1
  FN: -1
  estimator: 'posterior'
  dpa:
    B486: [1,1]
    B497: [1,1]
    B500: [1,1]

    
