Global:
  outdir: /cluster/work/bewi/members/dondia/projects/long_reads_tree/LongSom_out/OvCa_LR
  data: /cluster/work/bewi/members/dondia/projects/long_reads_tree/data/SComatic_input/OvCa_LR
  qc: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/LongSom/QC/scripts
  scomatic: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/LongSom/SComatic/scripts
  bnpc: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/LongSom/BnpC
  annovar: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/annovar
  subread: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/subread-2.0.6-source
  infercnv: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/LongSom/InferCNV
  genome: /cluster/work/bewi/members/dondia/projects/ovarian_cancer/reference/hg38.fa
  isoforms: /cluster/work/bewi/members/dondia/projects/ovarian_cancer/reference/gencode.v36.annotation.gtf
  ids:
    B486: ""
    B497: ""
    B500: ""

PoN:
  celltypes:
    Normal: ""
  ids:
    B486_Norm: ""
    B500_Norm: ""
  min_ac_cells: 1
  min_ac_reads: 1
  min_cells: 1
  min_cell_types: 1

CellTypeReannotation:
  cancer_ctype: HGSOC
  noncancer_ctype: Non-HGSOC
  ctypes: ['HGSOC', 'Non-HGSOC']
  celltypes:
    HGSOC: ""
    Non-HGSOC: ""
  ctype_column: Automated_Cell_type
  chrM_contaminant: 'False'

  min_variants: 3
  
  HCCV:
    min_depth: 20
    deltaVAF: 0.25
    deltaCCF: 0.4

SNVCalling:
  cancer_ctype: Cancer
  celltypes:
    Cancer: ""
    NonCancer: ""
  min_ac_reads: 3
  clust_dist: 10000
  clustermap:
    height: 10
    width: 15

scDNA:
  Tumor_clone: 'Clone_Tum'
  NonTumor_clone: 'Clone_NonTum'
  BaseCellCounter:
    min_mapping_quality: 30
    min_dp: 5
    min_cc: 2  
  BaseCellCalling:
    min_ac_cells: 2
    min_ac_reads: 3


SComatic:
  chrM_contaminant: 'True'
  BaseCellCounter:
    min_mapping_quality: 60
    chromosomes: all  

  BaseCellCalling:
    Min_cell_types: 2
    RNA_editing: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/SComatic/RNAediting/AllEditingSites.hg38.txt
    min_distance: 0
    PoN_SR: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/SComatic/PoNs/PoN.scRNAseq.hg38.tsv
    gnomAD_db: /cluster/work/bewi/members/dondia/projects/long_reads_tree/ref/gnomAD
    max_gnomAD_VAF: 0.01
    deltaVAF: 0.1
    deltaCCF: 0.3

  SingleCellGenotype:
    alt_flag: All
    pvalue: 0.01

BnpC:
  outdir: '3kSteps.0.001-5dpa'
  min_cells_per_mut: 5
  min_pos_cov: 3
  mcmc_steps: 3000
  cup: 0
  eup: 0
  FP: -1
  FN: -1
  estimator: 'posterior'
  pp: [1,1]
  dpa:
    B486: [0.001,5]
    B497: [1,1]
    B500: [1,1]
  mut_order:
    B486: '' #/cluster/work/bewi/members/dondia/projects/long_reads_tree/LongSom_out/OvCa_LR/BnpC/BnpC_input/B486.order.tsv
    B497: ''
    B500: ''
  
inferCNV:
  ordering: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/LongSom/InferCNV/gene_ordering_file.txt
