# LongSom config yaml file

Run:
  # Run cell type reannotation
  reanno: True
  # Run SNV calling with SComatic
  scomatic: True
  # Run SNV annotation with annovar
  annovar: False
  # Run cell clustering with BnpC
  bnpc: True
  # Run fusion calling with CTAT-LR-Fusion
  ctatfusion: False
  # Run CNV calling with InferCNV
  infercnv: False
  # Generate various plots
  plot: False
  # Run scDNA validation (DEV only)
  scdna: False
  
Global:
  outdir: /cluster/work/bewi/members/dondia/projects/long_reads_tree/LongSom_out/OvCa_SR
  data: /cluster/work/bewi/members/dondia/projects/long_reads_tree/data/SComatic_input/OvCa_SR
  qc: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/LongSom/QC/scripts
  scomatic: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/LongSom/SComatic/scripts
  bnpc: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/LongSom/BnpC
  annovar: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/annovar
  subread: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/subread-2.0.6-source
  infercnv: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/LongSom/InferCNV
  genome: /cluster/work/bewi/members/dondia/projects/ovarian_cancer/reference/Homo_sapiens.GRCh38.dna.toplevel.fa
  isoforms: /cluster/work/bewi/members/dondia/projects/ovarian_cancer/reference/gencode.v36.annotation.gtf
  ids:
    B486: ""
    B497: ""
    B500: ""

PoN:
  celltypes:
    Normal: ""
  ids:
    B486_Norm: ""
    B500_Norm: ""
  min_ac_cells: 1
  min_ac_reads: 1
  min_cells: 1
  min_cell_types: 1

CellTypeReannotation:
  cancer_ctype: HGSOC
  noncancer_ctype: Non-HGSOC
  ctypes: ['HGSOC', 'Non-HGSOC']
  celltypes:
    HGSOC: ""
    Non-HGSOC: ""
  ctype_column: Automated_Cell_type
  chrM_contaminant: 'False'
  HCCV:
    min_depth: 20
    deltaVAF: 0.25
    deltaCCF: 0.4
  Reannotation:
    min_variants: 3
    min_fraction: 0.25

SNVCalling:
  cancer_ctype: Cancer
  celltypes:
    Cancer: ""
    NonCancer: ""
  min_ac_reads: 3
  min_ac_cells: 2
  clust_dist: 10000
  clustermap:
    height: 10
    width: 15

scDNA:
  Tumor_clone: 'Clone_Tum'
  NonTumor_clone: 'Clone_NonTum'
  BaseCellCounter:
    min_mapping_quality: 30
    min_dp: 5
    min_cc: 2  
  BaseCellCalling:
    min_ac_cells: 2
    min_ac_reads: 3

scDNAValidation:
  min_depth: 17

SComatic:
  chrM_contaminant: 'True'
  BaseCellCounter:
    min_mapping_quality: 255
    chromosomes: all  

  BaseCellCalling:
    Min_cell_types: 2
    RNA_editing: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/SComatic/RNAediting/AllEditingSites.hg38.no_chr_prefix.txt
    min_distance: 0
    PoN_SR: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/SComatic/PoNs/PoN.scRNAseq.hg38.no_chr_prefix.tsv
    gnomAD_db: /cluster/work/bewi/members/dondia/projects/long_reads_tree/ref/gnomAD
    max_gnomAD_VAF: 0.01
    deltaVAF: 0.1
    deltaCCF: 0.3
    min_ac_cells: 1
    min_ac_reads: 1

  SingleCellGenotype:
    alt_flag: All
    pvalue: 0.01

BnpC:
  outdir: '3kSteps.0.001-5dpa'
  min_cells_per_mut: 1
  min_pos_cov: 1
  mcmc_steps: 3000
  cup: 0
  eup: 0
  FP: -1
  FN: -1
  estimator: 'posterior'
  pp: [1,1]
  dpa:
    B486: [0.001,5]
    B497: [1,1]
    B500: [1,1]
  mut_order:
    B486: ''
    B497: ''
    B500: ''
  
inferCNV:
  ordering: /cluster/work/bewi/members/dondia/projects/long_reads_tree/bin/LongSom/InferCNV/gene_ordering_file.txt
