# LongSom config yaml file

# Change those values to yours
User:
  input_dir: /path/to/input_dir
  output_dir: /path/to/output_dir
  sample_map: /path/to/sample_map.tsv
  cancer_cell_type: HGSOC
  
# Change if you use a custom reference
Reference:
  genome: /../ref/GRCh38_gencode_v44_CTAT_lib_Oct292023.plug-n-play/ctat_genome_lib_build_dir/ref_genome.fa
  isoforms: /../ref/GRCh38_gencode_v44_CTAT_lib_Oct292023.plug-n-play/ctat_genome_lib_build_dir/ref_annot.gtf
  gnomAD_db: /../ref/gnomAD_v4.1
  RNA_editing: /../ref/AllEditingSites.hg38.txt.gz
  PoN_SR: /../ref/PoN.scRNAseq.hg38.tsv.gz 

# Change any of those to True if you want to run it, else False
Run:
  # Create a PoN based on Normals
  PoN: False
  # Run cell type reannotation
  CellTypeReannotation: True
  # Run SNV calling with SComatic
  SNVCalling: True
  # Run cell clustering with BnpC
  CellClustering: True
  # Run fusion calling with CTAT-LR-Fusion
  FusionCalling: True
  # Run CNV calling with InferCNV
  CNACalling: False

PoN:
  min_ac_cells: 1
  min_ac_reads: 1
  min_cells: 1
  min_cell_types: 1

### Cell Type Reannotation
Reanno:

  BaseCellCounter:
    min_mapping_quality: 60
    chromosomes: all  

  BaseCellCalling:
    Min_cell_types: 2
    min_distance: 0
    max_gnomAD_VAF: 0.01
    min_ac_cells: 5
    min_ac_reads: 20
    alpha1: 0.21356677091082193
    beta1: 104.95163748636298
    alpha2: 0.2474528917555431
    beta2: 162.03696139428595

  HCCV:
    min_depth: 50
    deltaVAF: 0.2
    deltaMCF: 0.25
    clust_dist: 10000
    chrM_contaminant: 'False'
    alt_flag: All
    pvalue: 0.01

  Reannotation:
    min_variants: 3
    min_fraction: 0.25

### SNV Calling
SNVCalling:
  
  BaseCellCounter:
    min_mapping_quality: 60
    chromosomes: all 

  BaseCellCalling:
    Min_cell_types: 2
    min_distance: 0
    max_gnomAD_VAF: 0.01
    deltaVAF: 0.05
    deltaMCF: 0.3
    min_ac_reads: 3
    min_ac_cells: 2
    clust_dist: 10000
    chrM_contaminant: 'True'
    alpha1: 0.21356677091082193
    beta1: 104.95163748636298
    alpha2: 0.2474528917555431
    beta2: 162.03696139428595

### Fusion Calling
FusionCalling:
  SomaticFusions:
    min_ac_reads: 3
    min_ac_cells: 2
    max_MCF_noncancer: 0.1
    deltaMCF: 0.3

### Cell Clustering
CellClust:

  SingleCellGenotype:
    alt_flag: All
    pvalue: 0.01

  FormatInput:
    min_cells_per_mut: 5
    min_pos_cov: 3
    
  BnpC:
    mcmc_steps: 1000
    cup: 0
    eup: 0
    FP: -1
    FN: -1
    estimator: 'posterior'
    pp: [1,1]
    dpa: [0.001, 5.0]

 ### CNA Calling 
inferCNV:
  ordering: ../scripts/CNACalling/gene_ordering_file.txt
